version: "3.7"

services:
  app:
    container_name: "sv-performance-test"
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    command: yarn start
    ports:
      - "3333:3333"
    volumes:
      - ".:/usr/app"
networks:
  default:
    external:
      name: arbocontrol-docker-testes_sv-network
