version: "3.7"

services:
  app:
    container_name: "sv-performance-test"
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    volumes:
      - ./output:/usr/app/output
    command: sh entrypoint.sh

networks:
  default:
    external:
      name: arbocontrol-docker-testes_sv-network
