version: "3.7"

services:
  app:
    container_name: "sv-performance-test"
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    volumes:
      - type: bind
        source: ./output
        target: /usr/app/output

networks:
  default:
    external:
      name: arbocontrol-docker-testes_sv-network
